### ISSUE TITLE
Toggling full window editor or app pushes toolbar off screen

### ISSUE THREAD

**Issue by cliffrowley** [leeola/appaid.kdapp#10]
Toggling any of the tabs (including Ace or AppAid itself) to full-window mode and back pushes the toolbar halfway off screen, as illustrated in [this screenshot](http://d.pr/i/QfqL/27qINdCC).

Steps to reproduce:
1. Open AppAid
2. Load an app
3. Toggle full window mode (CMD/CTRL+Enter)
4. Toggle normal window mode (CMD/CTRL+Enter)
5. Observe toolbar

**Comment by leeola** [comment]
Ah, you're in the develop branch i see hehe

Yea, i'm undecided if i'm going to pull this feature or not. It has proven buggy for me, even unlreated to this issue.

Regarding the size of the bar, i have no clue how to deal with it. It's the KD framework auto adjusting dimensions, and has proven difficult in the past.

The same thing happens if you shrink the app and make the window big again, eg: http://d.pr/i/3nid

So this isn't a problem with fullscreen, it's a problem with the app dimensions itself. It's like the KD framework autoadjusts widths, but doesn't readjust frequently enough.

**Comment by cliffrowley** [comment]
Yeah I'm using master branch.  Should I be using a tag or release branch?

Regarding the toolbar - hmm, I'll maybe see if I can help too - I'm already playing with KD and I will most certainly want to answer questions like this for myself anyway!

On 4 September 2013 at 15:19:52, Lee Olayvar (notifications@github.com) wrote:

Ah, you're in the develop branch i see hehe

Yea, i'm undecided if i'm going to pull this feature or not. It has proven buggy for me, even unlreated to this issue.

Regarding the size of the bar, i have no clue how to deal with it. It's the KD framework auto adjusting dimensions, and has proven difficult in the past.

The same thing happens if you shrink the app and make the window big again, eg: http://d.pr/i/3nid

So this isn't a problem with fullscreen, it's a problem with the app dimensions itself. It's like the KD framework autoadjusts widths, but doesn't readjust frequently enough.

**Comment by leeola** [comment]
Wait, master branch? No the master branch should be the latest "stable" (for an experimental app lol).

The reason i thought you were using the develop branch, is because you're using a feature that i added last night. The master branch looks like this:

```
do ->
  console.log "AppAid Loaded into id:#{appView.id}"

  # Our MainView instance, which is assigned in `./app/views.coffee`.
  mainView = new MainView()
  appView.addSubView mainView
```

where as the develop has a ctrl-enter hotkey:

```
do ->
  console.log "AppAid Loaded into id:#{appView.id}"

  # I don't think this is the proper way to enable binds. We're binding to
  # the global state, which is probably not what we want. Currently i am not
  # aware of a better way to bind the keys though.
  Mousetrap.bind ['command+enter', 'ctrl+enter'],
    -> KD.getSingleton('mainView').toggleFullscreen()

  # Our MainView instance, which is assigned in `./app/views.coffee`.
  mainView = new MainView()
  appView.addSubView mainView
```

But it's buggy as hell, and i'm not a fan of it.

I think what you were seeing was a bug in the framework? Eg, if i select an Ace tab, and then select my AppAid tab, i can use Ctrl+Enter on the app, even though the app doesn't have this enabled/bound. Feels like Koding is leaking the keybinds.

In regards to the develop branch feature, it's too general currently. When i bind that, it works _everywhere_. I need to figure out how to bind keys in just my app.

**Comment by cliffrowley** [comment]
Lol you are so ass backwards sometimes :-P master should be the develop branch :-P

Anyway, the hot key isn't actually the issue. Try going to Ace, doing full/normal toggle there, then come back to AppAid and the toolbar has shifted.

**Comment by leeola** [comment]
Oh god, your master is your develop branch!? Wtf is your release branch?

I follow http://nvie.com/posts/a-successful-git-branching-model/ for sanity :P. Granted, in recent times i have abandoned no-ff, because most "advanced" git users agree that it just creates needless commit messages (and i have become annoyed by it). Default (which is master) should always be the stable branch, imo.

Anyway, back on topic, i am aware it's not a fullscreen toggle, that's what i meant earlier by:

> The same thing happens if you shrink the app and make the window big again, eg: http://d.pr/i/3nid

You don't even need to fullscreen, simply resize the window (for me at least).

**Comment by cliffrowley** [comment]
Lol yes, mine and oh I don't know - the rest of the world? :-P  There's no such thing as a "release branch", that's what tags are for, why on earth would you need a "release branch" when that code is released (usually with a version number, which in this case corresponds to the tag name)? ;-)

RE toolbar - I see.  I just thought you were confusing what I was saying (otherwise I have no idea why you mentioned your keyboard shortcut code!).

**Comment by leeola** [comment]
> Lol yes, mine and oh I don't know - the rest of the world? :-P There's no such thing as a "release branch", that's what tags are for, why on earth would you need a "release branch" when that code is released (usually with a version number, which in this case corresponds to the tag name)? ;-)

You sicken me! (hehe)

> RE toolbar - I see. I just thought you were confusing what I was saying (otherwise I have no idea why you mentioned your keyboard shortcut code!).

 I just have no idea what might be causing this. Have you seen it in any other apps?

**Comment by cliffrowley** [comment]
1. Haha, then you must be sickened by the rest of the world (seriously!) - have a look around ;-)
2. I haven't seen it in any other apps, no, but then I don't use many..  Hrmm.

I know it's off topic, but you know I like talking about these things :-P  Just to (very briefly) clarify the workflow I use (and honestly, so do the majority of people) - master is the latest cut of the code, it's never unstable, it's just the latest that is _ready to be released_.  There's no such thing as a "develop" branch because _all_ work takes place in feature based topic branches, which are later merged into master after passing their tests and being sanity checked (we do code reviews often) - then when master is deemed ready for release, it's tagged and released.  The reason for this is mainly because when you clone a repository, you're _usually_ doing so in order to work on it, not to use it, and typically you wouldn't be working in a "release branch".

**Comment by leeola** [comment]
> master is the latest cut of the code, it's never unstable

Not that different to [this](http://nvie.com/git-model/), it's just that the nvie model goes one step further and says master is always production ready, and is assumed to be a production release at any state. The head of the branch, is by definition, production. Rather than having to check which tag production is currently at, and allowing for git hook releases.

If master is just any stable release, then you have to make side branches outside of master for code freezes/etc. I prefer the one way model (all code flows into one point).

Anyway, we're super off topic. Bring it up in Skype if you like :P
